from pydantic import Field

from .base import StrictBaseModel


class TeamStatsAdditionalInfo(StrictBaseModel):
    attack_num_recoded_matches_home: int
    attack_num_recoded_matches_away: int
    dangerous_attacks_num_home: int
    dangerous_attacks_num_away: int
    attacks_num_home: int
    attacks_num_away: int
    xg_for_overall: float
    xg_for_home: float
    xg_for_away: float
    xg_against_overall: float
    xg_against_home: float
    xg_against_away: float
    seasonScoredOver35Num_overall: int
    seasonScoredOver25Num_overall: int
    seasonScoredOver15Num_overall: int
    seasonScoredOver05Num_overall: int
    seasonScoredOver35Percentage_overall: int
    seasonScoredOver25Percentage_overall: int
    seasonScoredOver15Percentage_overall: int
    seasonScoredOver05Percentage_overall: int
    seasonScoredOver35Num_home: int
    seasonScoredOver25Num_home: int
    seasonScoredOver15Num_home: int
    seasonScoredOver05Num_home: int
    seasonScoredOver35Percentage_home: int
    seasonScoredOver25Percentage_home: int
    seasonScoredOver15Percentage_home: int
    seasonScoredOver05Percentage_home: int
    seasonScoredOver35Num_away: int
    seasonScoredOver25Num_away: int
    seasonScoredOver15Num_away: int
    seasonScoredOver05Num_away: int
    seasonScoredOver35Percentage_away: int
    seasonScoredOver25Percentage_away: int
    seasonScoredOver15Percentage_away: int
    seasonScoredOver05Percentage_away: int
    seasonConcededOver35Num_overall: int
    seasonConcededOver25Num_overall: int
    seasonConcededOver15Num_overall: int
    seasonConcededOver05Num_overall: int
    seasonConcededOver35Percentage_overall: int
    seasonConcededOver25Percentage_overall: int
    seasonConcededOver15Percentage_overall: int
    seasonConcededOver05Percentage_overall: int
    seasonConcededOver35Num_home: int
    seasonConcededOver25Num_home: int
    seasonConcededOver15Num_home: int
    seasonConcededOver05Num_home: int
    seasonConcededOver35Percentage_home: int
    seasonConcededOver25Percentage_home: int
    seasonConcededOver15Percentage_home: int
    seasonConcededOver05Percentage_home: int
    formRun_overall: str
    formRun_home: str
    formRun_away: str
    seasonConcededOver35Num_away: int
    seasonConcededOver25Num_away: int
    seasonConcededOver15Num_away: int
    seasonConcededOver05Num_away: int
    seasonConcededOver35Percentage_away: int
    seasonConcededOver25Percentage_away: int
    seasonConcededOver15Percentage_away: int
    seasonConcededOver05Percentage_away: int
    cardTimingRecorded_matches_overall: int
    cardTimingRecorded_matches_home: int
    cardTimingRecorded_matches_away: int
    cardsRecorded_matches_overall: int
    cardsRecorded_matches_home: int
    cardsRecorded_matches_away: int
    fh_cards_total_overall: int
    fh_cards_total_home: int
    fh_cards_total_away: int
    x_2h_cards_total_overall: int = Field(alias="2h_cards_total_overall")
    x_2h_cards_total_home: int = Field(alias="2h_cards_total_home")
    x_2h_cards_total_away: int = Field(alias="2h_cards_total_away")
    fh_cards_for_overall: int
    fh_cards_for_home: int
    fh_cards_for_away: int
    x_2h_cards_for_overall: int = Field(alias="2h_cards_for_overall")
    x_2h_cards_for_home: int = Field(alias="2h_cards_for_home")
    x_2h_cards_for_away: int = Field(alias="2h_cards_for_away")
    fh_cards_against_overall: int
    fh_cards_against_home: int
    fh_cards_against_away: int
    x_2h_cards_against_overall: int = Field(alias="2h_cards_against_overall")
    x_2h_cards_against_home: int = Field(alias="2h_cards_against_home")
    x_2h_cards_against_away: int = Field(alias="2h_cards_against_away")
    fh_cards_for_avg_overall: float
    fh_cards_for_avg_home: float
    fh_cards_for_avg_away: float
    x_2h_cards_for_avg_overall: float = Field(alias="2h_cards_for_avg_overall")
    x_2h_cards_for_avg_home: float = Field(alias="2h_cards_for_avg_home")
    x_2h_cards_for_avg_away: float = Field(alias="2h_cards_for_avg_away")
    fh_cards_against_avg_overall: float
    fh_cards_against_avg_home: float
    fh_cards_against_avg_away: float
    x_2h_cards_against_avg_overall: float = Field(alias="2h_cards_against_avg_overall")
    x_2h_cards_against_avg_home: float = Field(alias="2h_cards_against_avg_home")
    x_2h_cards_against_avg_away: float = Field(alias="2h_cards_against_avg_away")
    fh_cards_total_avg_overall: float
    fh_cards_total_avg_home: float
    fh_cards_total_avg_away: float
    x_2h_cards_total_avg_overall: float = Field(alias="2h_cards_total_avg_overall")
    x_2h_cards_total_avg_home: float = Field(alias="2h_cards_total_avg_home")
    x_2h_cards_total_avg_away: float = Field(alias="2h_cards_total_avg_away")
    fh_total_cards_under2_percentage_overall: int
    fh_total_cards_under2_percentage_home: int
    fh_total_cards_under2_percentage_away: int
    fh_total_cards_2to3_percentage_overall: int
    fh_total_cards_2to3_percentage_home: int
    fh_total_cards_2to3_percentage_away: int
    fh_total_cards_over3_percentage_overall: int
    fh_total_cards_over3_percentage_home: int
    fh_total_cards_over3_percentage_away: int
    match_shots_over225_num_overall: int | None = None
    match_shots_over225_num_home: int | None = None
    match_shots_over225_num_away: int | None = None
    match_shots_over225_percentage_overall: int | None = None
    match_shots_over225_percentage_home: int | None = None
    match_shots_over225_percentage_away: int | None = None
    x_2h_total_cards_under2_percentage_overall: int = Field(
        alias="2h_total_cards_under2_percentage_overall"
    )
    x_2h_total_cards_under2_percentage_home: int = Field(
        alias="2h_total_cards_under2_percentage_home"
    )
    x_2h_total_cards_under2_percentage_away: int = Field(
        alias="2h_total_cards_under2_percentage_away"
    )
    x_2h_total_cards_2to3_percentage_overall: int = Field(
        alias="2h_total_cards_2to3_percentage_overall"
    )
    x_2h_total_cards_2to3_percentage_home: int = Field(
        alias="2h_total_cards_2to3_percentage_home"
    )
    x_2h_total_cards_2to3_percentage_away: int = Field(
        alias="2h_total_cards_2to3_percentage_away"
    )
    x_2h_total_cards_over3_percentage_overall: int = Field(
        alias="2h_total_cards_over3_percentage_overall"
    )
    x_2h_total_cards_over3_percentage_home: int = Field(
        alias="2h_total_cards_over3_percentage_home"
    )
    x_2h_total_cards_over3_percentage_away: int = Field(
        alias="2h_total_cards_over3_percentage_away"
    )
    fh_half_with_most_cards_total_percentage_overall: int
    fh_half_with_most_cards_total_percentage_home: int
    fh_half_with_most_cards_total_percentage_away: int
    x_2h_half_with_most_cards_total_percentage_overall: int = Field(
        alias="2h_half_with_most_cards_total_percentage_overall"
    )
    x_2h_half_with_most_cards_total_percentage_home: int = Field(
        alias="2h_half_with_most_cards_total_percentage_home"
    )
    x_2h_half_with_most_cards_total_percentage_away: int = Field(
        alias="2h_half_with_most_cards_total_percentage_away"
    )
    fh_cards_for_over05_percentage_overall: int
    fh_cards_for_over05_percentage_home: int
    fh_cards_for_over05_percentage_away: int
    x_2h_cards_for_over05_percentage_overall: int = Field(
        alias="2h_cards_for_over05_percentage_overall"
    )
    x_2h_cards_for_over05_percentage_home: int = Field(
        alias="2h_cards_for_over05_percentage_home"
    )
    x_2h_cards_for_over05_percentage_away: int = Field(
        alias="2h_cards_for_over05_percentage_away"
    )
    cards_for_overall: int
    cards_for_home: int
    cards_for_away: int
    cards_against_overall: int
    cards_against_home: int
    cards_against_away: int
    cards_for_avg_overall: float
    cards_for_avg_home: float
    cards_for_avg_away: float
    cards_against_avg_overall: float
    cards_against_avg_home: float
    cards_against_avg_away: float
    cards_total_overall: int
    cards_total_home: int
    cards_total_away: int
    cards_total_avg_overall: float
    cards_total_avg_home: float
    cards_total_avg_away: float
    penalties_won_overall: int
    penalties_won_home: int
    penalties_won_away: int
    penalties_scored_overall: int
    penalties_scored_home: int
    penalties_scored_away: int
    penalties_missed_overall: int
    penalties_missed_home: int
    penalties_missed_away: int
    penalties_won_per_match_overall: float
    penalties_won_per_match_home: float
    penalties_won_per_match_away: float
    penalties_recorded_matches_overall: int
    penalties_recorded_matches_home: int
    penalties_recorded_matches_away: int
    exact_team_goals_0_ft_overall: int
    exact_team_goals_1_ft_overall: int
    exact_team_goals_2_ft_overall: int
    exact_team_goals_3_ft_overall: int
    exact_team_goals_1_ft_home: int
    exact_team_goals_2_ft_home: int
    exact_team_goals_3_ft_home: int
    exact_team_goals_0_ft_away: int
    exact_team_goals_1_ft_away: int
    exact_team_goals_2_ft_away: int
    exact_team_goals_3_ft_away: int
    match_shots_over235_num_overall: int
    match_shots_over245_num_overall: int
    match_shots_over255_num_overall: int
    match_shots_over265_num_overall: int
    match_shots_over235_num_home: int
    match_shots_over245_num_home: int
    match_shots_over255_num_home: int
    match_shots_over265_num_home: int
    match_shots_over235_num_away: int
    match_shots_over245_num_away: int
    match_shots_over255_num_away: int
    match_shots_over265_num_away: int
    match_shots_over235_percentage_overall: int
    match_shots_over245_percentage_overall: int
    match_shots_over255_percentage_overall: int
    match_shots_over265_percentage_overall: int
    match_shots_over235_percentage_home: int
    match_shots_over245_percentage_home: int
    match_shots_over255_percentage_home: int
    match_shots_over265_percentage_home: int
    match_shots_over235_percentage_away: int
    match_shots_over245_percentage_away: int
    match_shots_over255_percentage_away: int
    match_shots_over265_percentage_away: int
    match_shots_on_target_over75_num_overall: int
    match_shots_on_target_over85_num_overall: int
    match_shots_on_target_over95_num_overall: int
    match_shots_on_target_over75_num_home: int
    match_shots_on_target_over85_num_home: int
    match_shots_on_target_over95_num_home: int
    match_shots_on_target_over75_num_away: int
    match_shots_on_target_over85_num_away: int
    match_shots_on_target_over95_num_away: int
    match_shots_on_target_over75_percentage_overall: int
    match_shots_on_target_over85_percentage_overall: int
    match_shots_on_target_over95_percentage_overall: int
    match_shots_on_target_over75_percentage_home: int
    match_shots_on_target_over85_percentage_home: int
    match_shots_on_target_over95_percentage_home: int
    match_shots_on_target_over75_percentage_away: int
    match_shots_on_target_over85_percentage_away: int
    match_shots_on_target_over95_percentage_away: int
    team_shots_over105_num_overall: int
    team_shots_over115_num_overall: int
    team_shots_over125_num_overall: int
    team_shots_over135_num_overall: int
    team_shots_over145_num_overall: int
    team_shots_over155_num_overall: int
    team_shots_over105_num_home: int
    team_shots_over115_num_home: int
    team_shots_over125_num_home: int
    team_shots_over135_num_home: int
    team_shots_over145_num_home: int
    team_shots_over155_num_home: int
    team_shots_over105_num_away: int
    team_shots_over115_num_away: int
    team_shots_over125_num_away: int
    team_shots_over135_num_away: int
    team_shots_over145_num_away: int
    team_shots_over155_num_away: int
    team_shots_over105_percentage_overall: int
    team_shots_over115_percentage_overall: int
    team_shots_over125_percentage_overall: int
    team_shots_over135_percentage_overall: int
    team_shots_over145_percentage_overall: int
    team_shots_over155_percentage_overall: int
    team_shots_over105_percentage_home: int
    team_shots_over115_percentage_home: int
    team_shots_over125_percentage_home: int
    team_shots_over135_percentage_home: int
    team_shots_over145_percentage_home: int
    team_shots_over155_percentage_home: int
    team_shots_over105_percentage_away: int
    team_shots_over115_percentage_away: int
    team_shots_over125_percentage_away: int
    team_shots_over135_percentage_away: int
    team_shots_over145_percentage_away: int
    team_shots_over155_percentage_away: int
    team_shots_on_target_over35_num_overall: int
    team_shots_on_target_over45_num_overall: int
    team_shots_on_target_over55_num_overall: int
    team_shots_on_target_over65_num_overall: int
    team_shots_on_target_over35_num_home: int
    team_shots_on_target_over45_num_home: int
    team_shots_on_target_over55_num_home: int
    team_shots_on_target_over65_num_home: int
    team_shots_on_target_over35_num_away: int
    team_shots_on_target_over45_num_away: int
    team_shots_on_target_over55_num_away: int
    team_shots_on_target_over65_num_away: int
    team_shots_on_target_over35_percentage_overall: int
    team_shots_on_target_over45_percentage_overall: int
    team_shots_on_target_over55_percentage_overall: int
    team_shots_on_target_over65_percentage_overall: int
    team_shots_on_target_over35_percentage_home: int
    team_shots_on_target_over45_percentage_home: int
    team_shots_on_target_over55_percentage_home: int
    team_shots_on_target_over65_percentage_home: int
    team_shots_on_target_over35_percentage_away: int
    team_shots_on_target_over45_percentage_away: int
    team_shots_on_target_over55_percentage_away: int
    team_shots_on_target_over65_percentage_away: int
    win_0_10_num_overall: int
    win_0_10_num_home: int
    win_0_10_num_away: int
    draw_0_10_num_overall: int
    draw_0_10_num_home: int
    draw_0_10_num_away: int
    loss_0_10_num_overall: int
    loss_0_10_num_home: int
    loss_0_10_num_away: int
    win_0_10_percentage_overall: int
    win_0_10_percentage_home: int
    win_0_10_percentage_away: int
    draw_0_10_percentage_overall: int
    draw_0_10_percentage_home: int
    draw_0_10_percentage_away: int
    loss_0_10_percentage_overall: int
    loss_0_10_percentage_home: int
    loss_0_10_percentage_away: int
    total_goal_over05_0_10_num_overall: int
    total_goal_over05_0_10_num_home: int
    total_goal_over05_0_10_num_away: int
    total_corner_over05_0_10_num_overall: int
    total_corner_over05_0_10_num_home: int
    total_corner_over05_0_10_num_away: int
    total_cards_over05_0_10_num_overall: int
    total_cards_over05_0_10_num_home: int
    total_cards_over05_0_10_num_away: int
    total_goal_over05_0_10_percentage_overall: int
    total_goal_over05_0_10_percentage_home: int
    total_goal_over05_0_10_percentage_away: int
    total_corner_over05_0_10_percentage_overall: int
    total_corner_over05_0_10_percentage_home: int
    total_corner_over05_0_10_percentage_away: int
    total_cards_over05_0_10_percentage_overall: int
    total_cards_over05_0_10_percentage_home: int
    total_cards_over05_0_10_percentage_away: int
    fouls_recorded_overall: int
    fouls_recorded_home: int
    fouls_recorded_away: int
    fouls_against_num_overall: int
    fouls_against_num_home: int
    fouls_against_num_away: int
    fouls_against_avg_overall: float
    fouls_against_avg_home: float
    fouls_against_avg_away: float
    exact_team_goals_0_ft_percentage_overall: int
    exact_team_goals_1_ft_percentage_overall: int
    exact_team_goals_2_ft_percentage_overall: int
    exact_team_goals_3_ft_percentage_overall: int
    exact_team_goals_0_ft_percentage_home: int
    exact_team_goals_1_ft_percentage_home: int
    exact_team_goals_2_ft_percentage_home: int
    exact_team_goals_3_ft_percentage_home: int
    exact_team_goals_0_ft_percentage_away: int
    exact_team_goals_1_ft_percentage_away: int
    exact_team_goals_2_ft_percentage_away: int
    exact_team_goals_3_ft_percentage_away: int
    exact_total_goals_0_ft_overall: int
    exact_total_goals_1_ft_overall: int
    exact_total_goals_2_ft_overall: int
    exact_total_goals_3_ft_overall: int
    exact_total_goals_4_ft_overall: int
    exact_total_goals_5_ft_overall: int
    exact_total_goals_6_ft_overall: int
    exact_total_goals_7_ft_overall: int
    exact_total_goals_0_ft_home: int
    exact_total_goals_1_ft_home: int
    exact_total_goals_2_ft_home: int
    exact_total_goals_3_ft_home: int
    exact_total_goals_4_ft_home: int
    exact_total_goals_5_ft_home: int
    exact_total_goals_6_ft_home: int
    exact_total_goals_7_ft_home: int
    exact_total_goals_0_ft_away: int
    exact_total_goals_1_ft_away: int
    exact_total_goals_2_ft_away: int
    exact_total_goals_3_ft_away: int
    exact_total_goals_4_ft_away: int
    exact_total_goals_5_ft_away: int
    exact_total_goals_6_ft_away: int
    exact_total_goals_7_ft_away: int
    shots_recorded_matches_num_overall: int
    shots_recorded_matches_num_home: int
    shots_recorded_matches_num_away: int
    over25_and_btts_num_overall: int
    over25_and_btts_num_home: int
    over25_and_btts_num_away: int
    over25_and_no_btts_num_overall: int
    over25_and_no_btts_num_home: int
    over25_and_no_btts_num_away: int
    over25_and_btts_percentage_overall: int
    over25_and_btts_percentage_home: int
    over25_and_btts_percentage_away: int
    over25_and_no_btts_percentage_overall: int
    over25_and_no_btts_percentage_home: int
    over25_and_no_btts_percentage_away: int
    btts_1h2h_yes_yes_num_overall: int
    btts_1h2h_yes_yes_num_home: int
    btts_1h2h_yes_yes_num_away: int
    btts_1h2h_yes_no_num_overall: int
    btts_1h2h_yes_no_num_home: int
    btts_1h2h_yes_no_num_away: int
    btts_1h2h_no_no_num_overall: int
    btts_1h2h_no_no_num_home: int
    btts_1h2h_no_no_num_away: int
    btts_1h2h_no_yes_num_overall: int
    btts_1h2h_no_yes_num_home: int
    btts_1h2h_no_yes_num_away: int
    half_with_most_goals_is_1h_num_overall: int
    half_with_most_goals_is_1h_num_home: int
    half_with_most_goals_is_1h_num_away: int
    half_with_most_goals_is_2h_num_overall: int
    half_with_most_goals_is_2h_num_home: int
    half_with_most_goals_is_2h_num_away: int
    half_with_most_goals_is_tie_num_overall: int
    half_with_most_goals_is_tie_num_home: int
    half_with_most_goals_is_tie_num_away: int
    half_with_most_goals_is_1h_percentage_overall: int
    half_with_most_goals_is_1h_percentage_home: int
    half_with_most_goals_is_1h_percentage_away: int
    half_with_most_goals_is_2h_percentage_overall: int
    half_with_most_goals_is_2h_percentage_away: int
    half_with_most_goals_is_tie_percentage_overall: int
    half_with_most_goals_is_tie_percentage_home: int
    half_with_most_goals_is_tie_percentage_away: int
    btts_1h2h_yes_yes_percentage_overall: int
    btts_1h2h_yes_yes_percentage_home: int
    btts_1h2h_yes_yes_percentage_away: int
    btts_1h2h_yes_no_percentage_overall: int
    btts_1h2h_yes_no_percentage_home: int
    btts_1h2h_yes_no_percentage_away: int
    btts_1h2h_no_no_percentage_overall: int
    btts_1h2h_no_no_percentage_home: int
    btts_1h2h_no_no_percentage_away: int
    btts_1h2h_no_yes_percentage_overall: int
    btts_1h2h_no_yes_percentage_home: int
    btts_1h2h_no_yes_percentage_away: int
    half_with_most_goals_is_2h_percentage_home: int
    shots_per_goals_scored_overall: float
    shots_per_goals_scored_home: float
    shots_per_goals_scored_away: float
    shots_on_target_per_goals_scored_overall: float
    shots_on_target_per_goals_scored_home: float
    shots_on_target_per_goals_scored_away: float
    shot_conversion_rate_overall: float
    shot_conversion_rate_home: float
    shot_conversion_rate_away: float
    team_with_most_corners_win_num_overall: int
    team_with_most_corners_win_num_home: int
    team_with_most_corners_win_num_away: int
    team_with_most_corners_win_1h_num_overall: int
    team_with_most_corners_win_1h_num_home: int
    team_with_most_corners_win_1h_num_away: int
    team_with_most_corners_win_2h_num_overall: int
    team_with_most_corners_win_2h_num_home: int
    team_with_most_corners_win_2h_num_away: int
    team_with_most_corners_win_percentage_overall: int
    team_with_most_corners_win_percentage_home: int
    team_with_most_corners_win_percentage_away: int
    team_with_most_corners_win_1h_percentage_overall: int
    team_with_most_corners_win_1h_percentage_home: int
    team_with_most_corners_win_1h_percentage_away: int
    team_with_most_corners_win_2h_percentage_overall: int
    team_with_most_corners_win_2h_percentage_home: int
    team_with_most_corners_win_2h_percentage_away: int
    half_with_most_corners_is_1h_num_overall: int
    half_with_most_corners_is_1h_num_home: int
    half_with_most_corners_is_1h_num_away: int
    half_with_most_corners_is_2h_num_overall: int
    half_with_most_corners_is_2h_num_home: int
    half_with_most_corners_is_2h_num_away: int
    half_with_most_corners_is_draw_num_overall: int
    half_with_most_corners_is_draw_num_home: int
    half_with_most_corners_is_draw_num_away: int
    half_with_most_corners_is_1h_percentage_overall: int
    half_with_most_corners_is_1h_percentage_home: int
    half_with_most_corners_is_1h_percentage_away: int
    half_with_most_corners_is_2h_percentage_overall: int
    half_with_most_corners_is_2h_percentage_home: int
    half_with_most_corners_is_2h_percentage_away: int
    half_with_most_corners_is_draw_percentage_overall: int
    half_with_most_corners_is_draw_percentage_home: int
    half_with_most_corners_is_draw_percentage_away: int
    corners_earned_1h_num_overall: int
    corners_earned_1h_num_home: int
    corners_earned_1h_num_away: int
    corners_earned_2h_num_overall: int
    corners_earned_2h_num_home: int
    corners_earned_2h_num_away: int
    corners_earned_1h_avg_overall: float
    corners_earned_1h_avg_home: float
    corners_earned_1h_avg_away: float
    corners_earned_2h_avg_overall: float
    corners_earned_2h_avg_home: float
    corners_earned_2h_avg_away: float
    corners_earned_1h_over2_num_overall: int
    corners_earned_1h_over2_num_home: int
    corners_earned_1h_over2_num_away: int
    corners_earned_1h_over3_num_overall: int
    corners_earned_1h_over3_num_home: int
    corners_earned_1h_over3_num_away: int
    corners_earned_2h_over2_num_overall: int
    corners_earned_2h_over2_num_home: int
    corners_earned_2h_over2_num_away: int
    corners_earned_2h_over3_num_overall: int
    corners_earned_2h_over3_num_home: int
    corners_earned_2h_over3_num_away: int
    corners_earned_1h_2_to_3_num_overall: int
    corners_earned_1h_2_to_3_num_home: int
    corners_earned_1h_2_to_3_num_away: int
    corners_earned_2h_2_to_3_num_overall: int
    corners_earned_2h_2_to_3_num_home: int
    corners_earned_2h_2_to_3_num_away: int
    corners_earned_1h_over2_percentage_overall: int
    corners_earned_1h_over2_percentage_home: int
    corners_earned_1h_over2_percentage_away: int
    corners_earned_1h_over3_percentage_overall: int
    corners_earned_1h_over3_percentage_home: int
    corners_earned_1h_over3_percentage_away: int
    corners_earned_2h_over2_percentage_overall: int
    corners_earned_2h_over2_percentage_home: int
    corners_earned_2h_over2_percentage_away: int
    corners_earned_2h_over3_percentage_overall: int
    corners_earned_2h_over3_percentage_home: int
    corners_earned_2h_over3_percentage_away: int
    corners_earned_1h_2_to_3_percentage_overall: int
    corners_earned_1h_2_to_3_percentage_home: int
    corners_earned_1h_2_to_3_percentage_away: int
    corners_earned_2h_2_to_3_percentage_overall: int
    corners_earned_2h_2_to_3_percentage_home: int
    corners_earned_2h_2_to_3_percentage_away: int
    penalties_conceded_overall: int
    penalties_conceded_home: int
    penalties_conceded_away: int
    penalty_in_a_match_overall: int
    penalty_in_a_match_home: int
    penalty_in_a_match_away: int
    penalty_in_a_match_percentage_overall: int
    penalty_in_a_match_percentage_home: int
    penalty_in_a_match_percentage_away: int
    goal_kicks_recorded_matches_overall: int
    goal_kicks_recorded_matches_home: int
    goal_kicks_recorded_matches_away: int
    goal_kicks_team_num_overall: int
    goal_kicks_team_num_home: int
    goal_kicks_team_num_away: int
    goal_kicks_total_num_overall: int
    goal_kicks_total_num_home: int
    goal_kicks_total_num_away: int
    goal_kicks_team_avg_overall: float
    goal_kicks_team_avg_home: float
    goal_kicks_team_avg_away: float
    goal_kicks_total_avg_overall: float
    goal_kicks_total_avg_home: float
    goal_kicks_total_avg_away: float
    goal_kicks_team_over35_overall: int
    goal_kicks_team_over35_home: int
    goal_kicks_team_over35_away: int
    goal_kicks_team_over45_overall: int
    goal_kicks_team_over45_home: int
    goal_kicks_team_over45_away: int
    goal_kicks_team_over55_overall: int
    goal_kicks_team_over55_home: int
    goal_kicks_team_over55_away: int
    goal_kicks_team_over65_overall: int
    goal_kicks_team_over65_home: int
    goal_kicks_team_over65_away: int
    goal_kicks_team_over75_overall: int
    goal_kicks_team_over75_home: int
    goal_kicks_team_over75_away: int
    goal_kicks_team_over85_overall: int
    goal_kicks_team_over85_home: int
    goal_kicks_team_over85_away: int
    goal_kicks_team_over95_overall: int
    goal_kicks_team_over95_home: int
    goal_kicks_team_over95_away: int
    goal_kicks_team_over105_overall: int
    goal_kicks_team_over105_home: int
    goal_kicks_team_over105_away: int
    goal_kicks_team_over115_overall: int
    goal_kicks_team_over115_home: int
    goal_kicks_team_over115_away: int
    goal_kicks_total_over85_overall: int
    goal_kicks_total_over85_home: int
    goal_kicks_total_over85_away: int
    goal_kicks_total_over95_overall: int
    goal_kicks_total_over95_home: int
    goal_kicks_total_over95_away: int
    goal_kicks_total_over105_overall: int
    goal_kicks_total_over105_home: int
    goal_kicks_total_over105_away: int
    goal_kicks_total_over115_overall: int
    goal_kicks_total_over115_home: int
    goal_kicks_total_over115_away: int
    goal_kicks_total_over125_overall: int
    goal_kicks_total_over125_home: int
    goal_kicks_total_over125_away: int
    goal_kicks_total_over135_overall: int
    goal_kicks_total_over135_home: int
    goal_kicks_total_over135_away: int
    goal_kicks_total_over145_overall: int
    goal_kicks_total_over145_home: int
    goal_kicks_total_over145_away: int
    goal_kicks_total_over155_overall: int
    goal_kicks_total_over155_home: int
    goal_kicks_total_over155_away: int
    goal_kicks_total_over165_overall: int
    goal_kicks_total_over165_home: int
    goal_kicks_total_over165_away: int
    goal_kicks_total_over175_overall: int
    goal_kicks_total_over175_home: int
    goal_kicks_total_over175_away: int
    goal_kicks_total_over185_overall: int
    goal_kicks_total_over185_home: int
    goal_kicks_total_over185_away: int
    throwins_recorded_matches_overall: int
    throwins_recorded_matches_home: int
    throwins_recorded_matches_away: int
    throwins_team_num_overall: int
    throwins_team_num_home: int
    throwins_team_num_away: int
    throwins_total_num_overall: int
    throwins_total_num_home: int
    throwins_total_num_away: int
    throwins_team_avg_overall: float
    throwins_team_avg_home: float
    throwins_team_avg_away: float
    throwins_total_avg_overall: float
    throwins_total_avg_home: float
    throwins_total_avg_away: float
    throwins_team_over155_overall: int
    throwins_team_over155_home: int
    throwins_team_over155_away: int
    throwins_team_over165_overall: int
    throwins_team_over165_home: int
    throwins_team_over165_away: int
    throwins_team_over175_overall: int
    throwins_team_over175_home: int
    throwins_team_over175_away: int
    throwins_team_over185_overall: int
    throwins_team_over185_home: int
    throwins_team_over185_away: int
    throwins_team_over195_overall: int
    throwins_team_over195_home: int
    throwins_team_over195_away: int
    throwins_team_over205_overall: int
    throwins_team_over205_home: int
    throwins_team_over205_away: int
    throwins_team_over215_overall: int
    throwins_team_over215_home: int
    throwins_team_over215_away: int
    throwins_team_over225_overall: int
    throwins_team_over225_home: int
    throwins_team_over225_away: int
    throwins_team_over235_overall: int
    throwins_team_over235_home: int
    throwins_team_over235_away: int
    throwins_team_over245_overall: int
    throwins_team_over245_home: int
    throwins_team_over245_away: int
    throwins_team_over255_overall: int
    throwins_team_over255_home: int
    throwins_team_over255_away: int
    throwins_total_over375_overall: int
    throwins_total_over375_home: int
    throwins_total_over375_away: int
    throwins_total_over385_overall: int
    throwins_total_over385_home: int
    throwins_total_over385_away: int
    throwins_total_over395_overall: int
    throwins_total_over395_home: int
    throwins_total_over395_away: int
    throwins_total_over405_overall: int
    throwins_total_over405_home: int
    throwins_total_over405_away: int
    throwins_total_over415_overall: int
    throwins_total_over415_home: int
    throwins_total_over415_away: int
    throwins_total_over425_overall: int
    throwins_total_over425_home: int
    throwins_total_over425_away: int
    throwins_total_over435_overall: int
    throwins_total_over435_home: int
    throwins_total_over435_away: int
    throwins_total_over445_overall: int
    throwins_total_over445_home: int
    throwins_total_over445_away: int
    throwins_total_over455_overall: int
    throwins_total_over455_home: int
    throwins_total_over455_away: int
    throwins_total_over465_overall: int
    throwins_total_over465_home: int
    throwins_total_over465_away: int
    throwins_total_over475_overall: int
    throwins_total_over475_home: int
    throwins_total_over475_away: int
    freekicks_recorded_matches_overall: int
    freekicks_recorded_matches_home: int
    freekicks_recorded_matches_away: int
    freekicks_team_num_overall: int
    freekicks_team_num_home: int
    freekicks_team_num_away: int
    freekicks_total_num_overall: int
    freekicks_total_num_home: int
    freekicks_total_num_away: int
    freekicks_team_avg_overall: float
    freekicks_team_avg_home: float
    freekicks_team_avg_away: float
    freekicks_total_avg_overall: float
    freekicks_total_avg_home: float
    freekicks_total_avg_away: float
    freekicks_team_over75_overall: int
    freekicks_team_over75_home: int
    freekicks_team_over75_away: int
    freekicks_team_over85_overall: int
    freekicks_team_over85_home: int
    freekicks_team_over85_away: int
    freekicks_team_over95_overall: int
    freekicks_team_over95_home: int
    freekicks_team_over95_away: int
    freekicks_team_over105_overall: int
    freekicks_team_over105_home: int
    freekicks_team_over105_away: int
    freekicks_team_over115_overall: int
    freekicks_team_over115_home: int
    freekicks_team_over115_away: int
    freekicks_team_over125_overall: int
    freekicks_team_over125_home: int
    freekicks_team_over125_away: int
    freekicks_team_over135_overall: int
    freekicks_team_over135_home: int
    freekicks_team_over135_away: int
    freekicks_team_over145_overall: int
    freekicks_team_over145_home: int
    freekicks_team_over145_away: int
    freekicks_team_over155_overall: int
    freekicks_team_over155_home: int
    freekicks_team_over155_away: int
    freekicks_team_over165_overall: int
    freekicks_team_over165_home: int
    freekicks_team_over165_away: int
    freekicks_team_over175_overall: int
    freekicks_team_over175_home: int
    freekicks_team_over175_away: int
    freekicks_total_over205_overall: int
    freekicks_total_over205_home: int
    freekicks_total_over205_away: int
    freekicks_total_over215_overall: int
    freekicks_total_over215_home: int
    freekicks_total_over215_away: int
    freekicks_total_over225_overall: int
    freekicks_total_over225_home: int
    freekicks_total_over225_away: int
    freekicks_total_over235_overall: int
    freekicks_total_over235_home: int
    freekicks_total_over235_away: int
    freekicks_total_over245_overall: int
    freekicks_total_over245_home: int
    freekicks_total_over245_away: int
    freekicks_total_over255_overall: int
    freekicks_total_over255_home: int
    freekicks_total_over255_away: int
    freekicks_total_over265_overall: int
    freekicks_total_over265_home: int
    freekicks_total_over265_away: int
    freekicks_total_over275_overall: int
    freekicks_total_over275_home: int
    freekicks_total_over275_away: int
    freekicks_total_over285_overall: int
    freekicks_total_over285_home: int
    freekicks_total_over285_away: int
    freekicks_total_over295_overall: int
    freekicks_total_over295_home: int
    freekicks_total_over295_away: int
    freekicks_total_over305_overall: int
    freekicks_total_over305_home: int
    freekicks_total_over305_away: int
