from pydantic import HttpUrl

from .base import StrictBaseModel
from .team_stats_addional_info import TeamStatsAdditionalInfo


class TeamStats(StrictBaseModel):
    suspended_matches: int
    homeAttackAdvantage: int
    homeDefenceAdvantage: int
    homeOverallAdvantage: int
    seasonGoals_overall: int
    seasonConceded_overall: int
    seasonGoalsTotal_overall: int
    seasonGoalsTotal_home: int
    seasonGoalsTotal_away: int
    seasonScoredNum_overall: int
    seasonScoredNum_home: int
    seasonScoredNum_away: int
    seasonConcededNum_overall: int
    seasonConcededNum_home: int
    seasonConcededNum_away: int
    seasonGoalsMin_overall: int
    seasonGoalsMin_home: int
    seasonGoalsMin_away: int
    seasonScoredMin_overall: int
    seasonScoredMin_home: int
    seasonScoredMin_away: int
    seasonConcededMin_overall: int
    seasonConcededMin_home: int
    seasonConcededMin_away: int
    seasonGoalDifference_overall: int
    seasonGoalDifference_home: int
    seasonGoalDifference_away: int
    seasonWinsNum_overall: int
    seasonWinsNum_home: int
    seasonWinsNum_away: int
    seasonDrawsNum_overall: int
    seasonDrawsNum_home: int
    seasonDrawsNum_away: int
    seasonLossesNum_overall: int
    seasonLossesNum_home: int
    seasonLossesNum_away: int
    seasonMatchesPlayed_overall: int
    seasonMatchesPlayed_away: int
    seasonMatchesPlayed_home: int
    seasonHighestScored_home: int
    seasonHighestConceded_home: int
    seasonHighestScored_away: int
    seasonHighestConceded_away: int
    seasonCS_overall: int
    seasonCS_home: int
    seasonCS_away: int
    seasonCSPercentage_overall: int
    seasonCSPercentage_home: int
    seasonCSPercentage_away: int
    seasonCSHT_overall: int
    seasonCSHT_home: int
    seasonCSHT_away: int
    seasonCSPercentageHT_overall: int
    seasonCSPercentageHT_home: int
    seasonCSPercentageHT_away: int
    seasonFTS_overall: int
    seasonFTSPercentage_overall: int
    seasonFTSPercentage_home: int
    seasonFTSPercentage_away: int
    seasonFTS_home: int
    seasonFTS_away: int
    seasonFTSHT_overall: int
    seasonFTSPercentageHT_overall: int
    seasonFTSPercentageHT_home: int
    seasonFTSPercentageHT_away: int
    seasonFTSHT_home: int
    seasonFTSHT_away: int
    seasonBTTS_overall: int
    seasonBTTS_home: int
    seasonBTTS_away: int
    seasonBTTSPercentage_overall: int
    seasonBTTSPercentage_home: int
    seasonBTTSPercentage_away: int
    seasonBTTSHT_overall: int
    seasonBTTSHT_home: int
    seasonBTTSHT_away: int
    seasonBTTSPercentageHT_overall: int
    seasonBTTSPercentageHT_home: int
    seasonBTTSPercentageHT_away: int
    seasonPPG_overall: float
    seasonPPG_home: float
    seasonPPG_away: float
    seasonAVG_overall: float
    seasonAVG_home: float
    seasonAVG_away: float
    seasonScoredAVG_overall: float
    seasonScoredAVG_home: float
    seasonScoredAVG_away: float
    seasonConcededAVG_overall: float
    seasonConcededAVG_home: float
    seasonConcededAVG_away: float
    winPercentage_overall: int
    winPercentage_home: int
    winPercentage_away: int
    drawPercentage_overall: int
    drawPercentage_home: int
    drawPercentage_away: int
    losePercentage_overall: int
    losePercentage_home: int
    losePercentage_away: int
    leadingAtHT_overall: int
    leadingAtHT_home: int
    leadingAtHT_away: int
    leadingAtHTPercentage_overall: int
    leadingAtHTPercentage_home: int
    leadingAtHTPercentage_away: int
    drawingAtHT_home: int
    drawingAtHT_away: int
    drawingAtHT_overall: int
    drawingAtHTPercentage_home: int
    drawingAtHTPercentage_away: int
    drawingAtHTPercentage_overall: int
    trailingAtHT_home: int
    trailingAtHT_away: int
    trailingAtHT_overall: int
    trailingAtHTPercentage_home: int
    trailingAtHTPercentage_away: int
    trailingAtHTPercentage_overall: int
    HTPoints_overall: int
    HTPoints_home: int
    HTPoints_away: int
    HTPPG_overall: float
    HTPPG_home: float
    HTPPG_away: float
    scoredAVGHT_overall: float
    scoredAVGHT_home: float
    scoredAVGHT_away: float
    concededAVGHT_overall: float
    concededAVGHT_home: float
    concededAVGHT_away: float
    AVGHT_overall: float
    AVGHT_home: float
    AVGHT_away: float
    scoredGoalsHT_overall: int
    scoredGoalsHT_home: int
    scoredGoalsHT_away: int
    concededGoalsHT_overall: int
    concededGoalsHT_home: int
    concededGoalsHT_away: int
    GoalsHT_overall: int
    GoalsHT_home: int
    GoalsHT_away: int
    GoalDifferenceHT_overall: int
    GoalDifferenceHT_home: int
    GoalDifferenceHT_away: int
    seasonOver55Num_overall: int
    seasonOver45Num_overall: int
    seasonOver35Num_overall: int
    seasonOver25Num_overall: int
    seasonOver15Num_overall: int
    seasonOver05Num_overall: int
    seasonOver55Percentage_overall: int
    seasonOver45Percentage_overall: int
    seasonOver35Percentage_overall: int
    seasonOver25Percentage_overall: int
    seasonOver15Percentage_overall: int
    seasonOver05Percentage_overall: int
    seasonUnder55Percentage_overall: int
    seasonUnder45Percentage_overall: int
    seasonUnder35Percentage_overall: int
    seasonUnder25Percentage_overall: int
    seasonUnder15Percentage_overall: int
    seasonUnder05Percentage_overall: int
    seasonUnder55Num_overall: int
    seasonUnder45Num_overall: int
    seasonUnder35Num_overall: int
    seasonUnder25Num_overall: int
    seasonUnder15Num_overall: int
    seasonUnder05Num_overall: int
    seasonOver55Percentage_home: int
    seasonOver45Percentage_home: int
    seasonOver35Percentage_home: int
    seasonOver25Percentage_home: int
    seasonOver15Percentage_home: int
    seasonOver05Percentage_home: int
    seasonOver55Num_home: int
    seasonOver45Num_home: int
    seasonOver35Num_home: int
    seasonOver25Num_home: int
    seasonOver15Num_home: int
    seasonOver05Num_home: int
    seasonUnder55Percentage_home: int
    seasonUnder45Percentage_home: int
    seasonUnder35Percentage_home: int
    seasonUnder25Percentage_home: int
    seasonUnder15Percentage_home: int
    seasonUnder05Percentage_home: int
    seasonUnder55Num_home: int
    seasonUnder45Num_home: int
    seasonUnder35Num_home: int
    seasonUnder25Num_home: int
    seasonUnder15Num_home: int
    seasonUnder05Num_home: int
    seasonOver55Percentage_away: int
    seasonOver45Percentage_away: int
    seasonOver35Percentage_away: int
    seasonOver25Percentage_away: int
    seasonOver15Percentage_away: int
    seasonOver05Percentage_away: int
    seasonOver55Num_away: int
    seasonOver45Num_away: int
    seasonOver35Num_away: int
    seasonOver25Num_away: int
    seasonOver15Num_away: int
    seasonOver05Num_away: int
    seasonUnder55Percentage_away: int
    seasonUnder45Percentage_away: int
    seasonUnder35Percentage_away: int
    seasonUnder25Percentage_away: int
    seasonUnder15Percentage_away: int
    seasonUnder05Percentage_away: int
    seasonUnder55Num_away: int
    seasonUnder45Num_away: int
    seasonUnder35Num_away: int
    seasonUnder25Num_away: int
    seasonUnder15Num_away: int
    seasonUnder05Num_away: int
    seasonOver25NumHT_overall: int
    seasonOver15NumHT_overall: int
    seasonOver05NumHT_overall: int
    seasonOver25PercentageHT_overall: int
    seasonOver15PercentageHT_overall: int
    seasonOver05PercentageHT_overall: int
    seasonOver25PercentageHT_home: int
    seasonOver15PercentageHT_home: int
    seasonOver05PercentageHT_home: int
    seasonOver25NumHT_home: int
    seasonOver15NumHT_home: int
    seasonOver05NumHT_home: int
    seasonOver25PercentageHT_away: int
    seasonOver15PercentageHT_away: int
    seasonOver05PercentageHT_away: int
    seasonOver25NumHT_away: int
    seasonOver15NumHT_away: int
    seasonOver05NumHT_away: int
    cornersRecorded_matches_overall: int
    cornersRecorded_matches_home: int
    cornersRecorded_matches_away: int
    over65Corners_overall: int
    over75Corners_overall: int
    over85Corners_overall: int
    over95Corners_overall: int
    over105Corners_overall: int
    over115Corners_overall: int
    over125Corners_overall: int
    over135Corners_overall: int
    over145Corners_overall: int
    over65CornersPercentage_overall: int
    over75CornersPercentage_overall: int
    over85CornersPercentage_overall: int
    over95CornersPercentage_overall: int
    over105CornersPercentage_overall: int
    over115CornersPercentage_overall: int
    over125CornersPercentage_overall: int
    over135CornersPercentage_overall: int
    over145CornersPercentage_overall: int
    over65Corners_home: int
    over75Corners_home: int
    over85Corners_home: int
    over95Corners_home: int
    over105Corners_home: int
    over115Corners_home: int
    over125Corners_home: int
    over135Corners_home: int
    over145Corners_home: int
    over65CornersPercentage_home: int
    over75CornersPercentage_home: int
    over85CornersPercentage_home: int
    over95CornersPercentage_home: int
    over105CornersPercentage_home: int
    over115CornersPercentage_home: int
    over125CornersPercentage_home: int
    over135CornersPercentage_home: int
    over145CornersPercentage_home: int
    over65Corners_away: int
    over75Corners_away: int
    over85Corners_away: int
    over95Corners_away: int
    over105Corners_away: int
    over115Corners_away: int
    over125Corners_away: int
    over135Corners_away: int
    over145Corners_away: int
    over65CornersPercentage_away: int
    over75CornersPercentage_away: int
    over85CornersPercentage_away: int
    over95CornersPercentage_away: int
    over105CornersPercentage_away: int
    over115CornersPercentage_away: int
    over125CornersPercentage_away: int
    over135CornersPercentage_away: int
    over145CornersPercentage_away: int
    over25CornersFor_overall: int
    over35CornersFor_overall: int
    over45CornersFor_overall: int
    over55CornersFor_overall: int
    over65CornersFor_overall: int
    over75CornersFor_overall: int
    over85CornersFor_overall: int
    over25CornersForPercentage_overall: int
    over35CornersForPercentage_overall: int
    over45CornersForPercentage_overall: int
    over55CornersForPercentage_overall: int
    over65CornersForPercentage_overall: int
    over75CornersForPercentage_overall: int
    over85CornersForPercentage_overall: int
    over25CornersFor_home: int
    over35CornersFor_home: int
    over45CornersFor_home: int
    over55CornersFor_home: int
    over65CornersFor_home: int
    over75CornersFor_home: int
    over85CornersFor_home: int
    over25CornersForPercentage_home: int
    over35CornersForPercentage_home: int
    over45CornersForPercentage_home: int
    over55CornersForPercentage_home: int
    over65CornersForPercentage_home: int
    over75CornersForPercentage_home: int
    over85CornersForPercentage_home: int
    over25CornersFor_away: int
    over35CornersFor_away: int
    over45CornersFor_away: int
    over55CornersFor_away: int
    over65CornersFor_away: int
    over75CornersFor_away: int
    over85CornersFor_away: int
    over25CornersForPercentage_away: int
    over35CornersForPercentage_away: int
    over45CornersForPercentage_away: int
    over55CornersForPercentage_away: int
    over65CornersForPercentage_away: int
    over75CornersForPercentage_away: int
    over85CornersForPercentage_away: int
    over25CornersAgainst_overall: int
    over35CornersAgainst_overall: int
    over45CornersAgainst_overall: int
    over55CornersAgainst_overall: int
    over65CornersAgainst_overall: int
    over75CornersAgainst_overall: int
    over85CornersAgainst_overall: int
    over25CornersAgainstPercentage_overall: int
    over35CornersAgainstPercentage_overall: int
    over45CornersAgainstPercentage_overall: int
    over55CornersAgainstPercentage_overall: int
    over65CornersAgainstPercentage_overall: int
    over75CornersAgainstPercentage_overall: int
    over85CornersAgainstPercentage_overall: int
    over25CornersAgainst_home: int
    over35CornersAgainst_home: int
    over45CornersAgainst_home: int
    over55CornersAgainst_home: int
    over65CornersAgainst_home: int
    over75CornersAgainst_home: int
    over85CornersAgainst_home: int
    over25CornersAgainstPercentage_home: int
    over35CornersAgainstPercentage_home: int
    over45CornersAgainstPercentage_home: int
    over55CornersAgainstPercentage_home: int
    over65CornersAgainstPercentage_home: int
    over75CornersAgainstPercentage_home: int
    over85CornersAgainstPercentage_home: int
    over25CornersAgainst_away: int
    over35CornersAgainst_away: int
    over45CornersAgainst_away: int
    over55CornersAgainst_away: int
    over65CornersAgainst_away: int
    over75CornersAgainst_away: int
    over85CornersAgainst_away: int
    over25CornersAgainstPercentage_away: int
    over35CornersAgainstPercentage_away: int
    over45CornersAgainstPercentage_away: int
    over55CornersAgainstPercentage_away: int
    over65CornersAgainstPercentage_away: int
    over75CornersAgainstPercentage_away: int
    over85CornersAgainstPercentage_away: int
    over05Cards_overall: int
    over15Cards_overall: int
    over25Cards_overall: int
    over35Cards_overall: int
    over45Cards_overall: int
    over55Cards_overall: int
    over65Cards_overall: int
    over75Cards_overall: int
    over85Cards_overall: int
    over05CardsPercentage_overall: int
    over15CardsPercentage_overall: int
    over25CardsPercentage_overall: int
    over35CardsPercentage_overall: int
    over45CardsPercentage_overall: int
    over55CardsPercentage_overall: int
    over65CardsPercentage_overall: int
    over75CardsPercentage_overall: int
    over85CardsPercentage_overall: int
    over05Cards_home: int
    over15Cards_home: int
    over25Cards_home: int
    over35Cards_home: int
    over45Cards_home: int
    over55Cards_home: int
    over65Cards_home: int
    over75Cards_home: int
    over85Cards_home: int
    over05CardsPercentage_home: int
    over15CardsPercentage_home: int
    over25CardsPercentage_home: int
    over35CardsPercentage_home: int
    over45CardsPercentage_home: int
    over55CardsPercentage_home: int
    over65CardsPercentage_home: int
    over75CardsPercentage_home: int
    over85CardsPercentage_home: int
    over05Cards_away: int
    over15Cards_away: int
    over25Cards_away: int
    over35Cards_away: int
    over45Cards_away: int
    over55Cards_away: int
    over65Cards_away: int
    over75Cards_away: int
    over85Cards_away: int
    over05CardsPercentage_away: int
    over15CardsPercentage_away: int
    over25CardsPercentage_away: int
    over35CardsPercentage_away: int
    over45CardsPercentage_away: int
    over55CardsPercentage_away: int
    over65CardsPercentage_away: int
    over75CardsPercentage_away: int
    over85CardsPercentage_away: int
    over05CardsFor_overall: int
    over15CardsFor_overall: int
    over25CardsFor_overall: int
    over35CardsFor_overall: int
    over45CardsFor_overall: int
    over55CardsFor_overall: int
    over65CardsFor_overall: int
    over05CardsForPercentage_overall: int
    over15CardsForPercentage_overall: int
    over25CardsForPercentage_overall: int
    over35CardsForPercentage_overall: int
    over45CardsForPercentage_overall: int
    over55CardsForPercentage_overall: int
    over65CardsForPercentage_overall: int
    over05CardsFor_home: int
    over15CardsFor_home: int
    over25CardsFor_home: int
    over35CardsFor_home: int
    over45CardsFor_home: int
    over55CardsFor_home: int
    over65CardsFor_home: int
    over05CardsForPercentage_home: int
    over15CardsForPercentage_home: int
    over25CardsForPercentage_home: int
    over35CardsForPercentage_home: int
    over45CardsForPercentage_home: int
    over55CardsForPercentage_home: int
    over65CardsForPercentage_home: int
    over05CardsFor_away: int
    over15CardsFor_away: int
    over25CardsFor_away: int
    over35CardsFor_away: int
    over45CardsFor_away: int
    over55CardsFor_away: int
    over65CardsFor_away: int
    over05CardsForPercentage_away: int
    over15CardsForPercentage_away: int
    over25CardsForPercentage_away: int
    over35CardsForPercentage_away: int
    over45CardsForPercentage_away: int
    over55CardsForPercentage_away: int
    over65CardsForPercentage_away: int
    over05CardsAgainst_overall: int
    over15CardsAgainst_overall: int
    over25CardsAgainst_overall: int
    over35CardsAgainst_overall: int
    over45CardsAgainst_overall: int
    over55CardsAgainst_overall: int
    over65CardsAgainst_overall: int
    over05CardsAgainstPercentage_overall: int
    over15CardsAgainstPercentage_overall: int
    over25CardsAgainstPercentage_overall: int
    over35CardsAgainstPercentage_overall: int
    over45CardsAgainstPercentage_overall: int
    over55CardsAgainstPercentage_overall: int
    over65CardsAgainstPercentage_overall: int
    over05CardsAgainst_home: int
    over15CardsAgainst_home: int
    over25CardsAgainst_home: int
    over35CardsAgainst_home: int
    over45CardsAgainst_home: int
    over55CardsAgainst_home: int
    over65CardsAgainst_home: int
    over05CardsAgainstPercentage_home: int
    over15CardsAgainstPercentage_home: int
    over25CardsAgainstPercentage_home: int
    over35CardsAgainstPercentage_home: int
    over45CardsAgainstPercentage_home: int
    over55CardsAgainstPercentage_home: int
    over65CardsAgainstPercentage_home: int
    over05CardsAgainst_away: int
    over15CardsAgainst_away: int
    over25CardsAgainst_away: int
    over35CardsAgainst_away: int
    over45CardsAgainst_away: int
    over55CardsAgainst_away: int
    over65CardsAgainst_away: int
    over05CardsAgainstPercentage_away: int
    over15CardsAgainstPercentage_away: int
    over25CardsAgainstPercentage_away: int
    over35CardsAgainstPercentage_away: int
    over45CardsAgainstPercentage_away: int
    over55CardsAgainstPercentage_away: int
    over65CardsAgainstPercentage_away: int
    leaguePosition_overall: int
    leaguePosition_home: int
    leaguePosition_away: int
    firstGoalScored_home: int
    firstGoalScored_away: int
    firstGoalScored_overall: int
    firstGoalScoredPercentage_home: int
    firstGoalScoredPercentage_away: int
    firstGoalScoredPercentage_overall: int
    cornersTotal_overall: int
    cornersTotal_home: int
    cornersTotal_away: int
    cardsTotal_overall: int
    cardsTotal_home: int
    cardsTotal_away: int
    cornersTotalAVG_overall: float
    cornersTotalAVG_home: float
    cornersTotalAVG_away: float
    cornersAVG_overall: float
    cornersAVG_home: float
    cornersAVG_away: float
    cornersAgainst_overall: int
    cornersAgainst_home: int
    cornersAgainst_away: int
    cornersAgainstAVG_overall: float
    cornersAgainstAVG_home: float
    cornersAgainstAVG_away: float
    cornersHighest_overall: int
    cornersLowest_overall: int
    cardsHighest_overall: int
    cardsLowest_overall: int
    cardsAVG_overall: float
    cardsAVG_home: float
    cardsAVG_away: float
    shotsTotal_overall: int
    shotsTotal_home: int
    shotsTotal_away: int
    shotsAVG_overall: float
    shotsAVG_home: float
    shotsAVG_away: float
    shotsOnTargetTotal_overall: int
    shotsOnTargetTotal_home: int
    shotsOnTargetTotal_away: int
    shotsOffTargetTotal_overall: int
    shotsOffTargetTotal_home: int
    shotsOffTargetTotal_away: int
    shotsOnTargetAVG_overall: float
    shotsOnTargetAVG_home: float
    shotsOnTargetAVG_away: float
    shotsOffTargetAVG_overall: float
    shotsOffTargetAVG_home: float
    shotsOffTargetAVG_away: float
    possessionAVG_overall: float
    possessionAVG_home: float
    possessionAVG_away: float
    foulsAVG_overall: float
    foulsAVG_home: float
    foulsAVG_away: float
    foulsTotal_overall: int
    foulsTotal_home: int
    foulsTotal_away: int
    offsidesTotal_overall: int
    offsidesTotal_home: int
    offsidesTotal_away: int
    offsidesTeamTotal_overall: int
    offsidesTeamTotal_home: int
    offsidesTeamTotal_away: int
    offsidesRecorded_matches_overall: int
    offsidesRecorded_matches_home: int
    offsidesRecorded_matches_away: int
    offsidesAVG_overall: float
    offsidesAVG_home: float
    offsidesAVG_away: float
    offsidesTeamAVG_overall: float
    offsidesTeamAVG_home: float
    offsidesTeamAVG_away: float
    offsidesOver05_overall: int
    offsidesOver15_overall: int
    offsidesOver25_overall: int
    offsidesOver35_overall: int
    offsidesOver45_overall: int
    offsidesOver55_overall: int
    offsidesOver65_overall: int
    over05OffsidesPercentage_overall: int
    over15OffsidesPercentage_overall: int
    over25OffsidesPercentage_overall: int
    over35OffsidesPercentage_overall: int
    over45OffsidesPercentage_overall: int
    over55OffsidesPercentage_overall: int
    over65OffsidesPercentage_overall: int
    offsidesOver05_home: int
    offsidesOver15_home: int
    offsidesOver25_home: int
    offsidesOver35_home: int
    offsidesOver45_home: int
    offsidesOver55_home: int
    offsidesOver65_home: int
    over05OffsidesPercentage_home: int
    over15OffsidesPercentage_home: int
    over25OffsidesPercentage_home: int
    over35OffsidesPercentage_home: int
    over45OffsidesPercentage_home: int
    over55OffsidesPercentage_home: int
    over65OffsidesPercentage_home: int
    offsidesOver05_away: int
    offsidesOver15_away: int
    offsidesOver25_away: int
    offsidesOver35_away: int
    offsidesOver45_away: int
    offsidesOver55_away: int
    offsidesOver65_away: int
    over05OffsidesPercentage_away: int
    over15OffsidesPercentage_away: int
    over25OffsidesPercentage_away: int
    over35OffsidesPercentage_away: int
    over45OffsidesPercentage_away: int
    over55OffsidesPercentage_away: int
    over65OffsidesPercentage_away: int
    offsidesTeamOver05_overall: int
    offsidesTeamOver15_overall: int
    offsidesTeamOver25_overall: int
    offsidesTeamOver35_overall: int
    offsidesTeamOver45_overall: int
    offsidesTeamOver55_overall: int
    offsidesTeamOver65_overall: int
    over05OffsidesTeamPercentage_overall: int
    over15OffsidesTeamPercentage_overall: int
    over25OffsidesTeamPercentage_overall: int
    over35OffsidesTeamPercentage_overall: int
    over45OffsidesTeamPercentage_overall: int
    over55OffsidesTeamPercentage_overall: int
    over65OffsidesTeamPercentage_overall: int
    offsidesTeamOver05_home: int
    offsidesTeamOver15_home: int
    offsidesTeamOver25_home: int
    offsidesTeamOver35_home: int
    offsidesTeamOver45_home: int
    offsidesTeamOver55_home: int
    offsidesTeamOver65_home: int
    over05OffsidesTeamPercentage_home: int
    over15OffsidesTeamPercentage_home: int
    over25OffsidesTeamPercentage_home: int
    over35OffsidesTeamPercentage_home: int
    over45OffsidesTeamPercentage_home: int
    over55OffsidesTeamPercentage_home: int
    over65OffsidesTeamPercentage_home: int
    offsidesTeamOver05_away: int
    offsidesTeamOver15_away: int
    offsidesTeamOver25_away: int
    offsidesTeamOver35_away: int
    offsidesTeamOver45_away: int
    offsidesTeamOver55_away: int
    offsidesTeamOver65_away: int
    over05OffsidesTeamPercentage_away: int
    over15OffsidesTeamPercentage_away: int
    over25OffsidesTeamPercentage_away: int
    over35OffsidesTeamPercentage_away: int
    over45OffsidesTeamPercentage_away: int
    over55OffsidesTeamPercentage_away: int
    over65OffsidesTeamPercentage_away: int
    scoredBothHalves_overall: int
    scoredBothHalves_home: int
    scoredBothHalves_away: int
    scoredBothHalvesPercentage_overall: int
    scoredBothHalvesPercentage_home: int
    scoredBothHalvesPercentage_away: int
    seasonMatchesPlayedGoalTimingRecorded_overall: int
    seasonMatchesPlayedGoalTimingRecorded_home: int
    seasonMatchesPlayedGoalTimingRecorded_away: int
    BTTS_and_win_overall: int
    BTTS_and_win_home: int
    BTTS_and_win_away: int
    BTTS_and_win_percentage_overall: int
    BTTS_and_win_percentage_home: int
    BTTS_and_win_percentage_away: int
    BTTS_and_draw_overall: int
    BTTS_and_draw_home: int
    BTTS_and_draw_away: int
    BTTS_and_draw_percentage_overall: int
    BTTS_and_draw_percentage_home: int
    BTTS_and_draw_percentage_away: int
    BTTS_and_lose_overall: int
    BTTS_and_lose_home: int
    BTTS_and_lose_away: int
    BTTS_and_lose_percentage_overall: int
    BTTS_and_lose_percentage_home: int
    BTTS_and_lose_percentage_away: int
    AVG_2hg_overall: float
    AVG_2hg_home: float
    AVG_2hg_away: float
    scored_2hg_avg_overall: float
    scored_2hg_avg_home: float
    scored_2hg_avg_away: float
    conceded_2hg_avg_overall: float
    conceded_2hg_avg_home: float
    conceded_2hg_avg_away: float
    total_2hg_overall: int
    total_2hg_home: int
    total_2hg_away: int
    conceded_2hg_overall: int
    conceded_2hg_home: int
    conceded_2hg_away: int
    scored_2hg_overall: int
    scored_2hg_home: int
    scored_2hg_away: int
    over25_2hg_num_overall: int
    over15_2hg_num_overall: int
    over05_2hg_num_overall: int
    over25_2hg_percentage_overall: int
    over15_2hg_percentage_overall: int
    over05_2hg_percentage_overall: int
    over25_2hg_num_home: int
    over15_2hg_num_home: int
    over05_2hg_num_home: int
    over25_2hg_percentage_home: int
    over15_2hg_percentage_home: int
    over05_2hg_percentage_home: int
    over25_2hg_num_away: int
    over15_2hg_num_away: int
    over05_2hg_num_away: int
    over25_2hg_percentage_away: int
    over15_2hg_percentage_away: int
    over05_2hg_percentage_away: int
    points_2hg_overall: int
    points_2hg_home: int
    points_2hg_away: int
    ppg_2hg_overall: float
    ppg_2hg_home: float
    ppg_2hg_away: float
    wins_2hg_overall: int
    wins_2hg_home: int
    wins_2hg_away: int
    wins_2hg_percentage_overall: int
    wins_2hg_percentage_home: int
    wins_2hg_percentage_away: int
    draws_2hg_overall: int
    draws_2hg_home: int
    draws_2hg_away: int
    draws_2hg_percentage_overall: int
    draws_2hg_percentage_home: int
    draws_2hg_percentage_away: int
    losses_2hg_overall: int
    losses_2hg_home: int
    losses_2hg_away: int
    losses_2hg_percentage_overall: int
    losses_2hg_percentage_home: int
    losses_2hg_percentage_away: int
    gd_2hg_overall: int
    gd_2hg_home: int
    gd_2hg_away: int
    btts_2hg_overall: int
    btts_2hg_home: int
    btts_2hg_away: int
    btts_2hg_percentage_overall: int
    btts_2hg_percentage_home: int
    btts_2hg_percentage_away: int
    btts_fhg_overall: int
    btts_fhg_home: int
    btts_fhg_away: int
    btts_fhg_percentage_overall: int
    btts_fhg_percentage_home: int
    btts_fhg_percentage_away: int
    cs_2hg_overall: int
    cs_2hg_home: int
    cs_2hg_away: int
    cs_2hg_percentage_overall: int
    cs_2hg_percentage_home: int
    cs_2hg_percentage_away: int
    fts_2hg_overall: int
    fts_2hg_home: int
    fts_2hg_away: int
    fts_2hg_percentage_overall: int
    fts_2hg_percentage_home: int
    fts_2hg_percentage_away: int
    BTTS_both_halves_overall: int
    BTTS_both_halves_home: int
    BTTS_both_halves_away: int
    BTTS_both_halves_percentage_overall: int
    BTTS_both_halves_percentage_home: int
    BTTS_both_halves_percentage_away: int
    average_attendance_overall: int
    average_attendance_home: int
    average_attendance_away: int
    cornerTimingRecorded_matches_overall: int
    cornerTimingRecorded_matches_home: int
    cornerTimingRecorded_matches_away: int
    corners_fh_overall: int
    corners_2h_overall: int
    corners_fh_home: int
    corners_2h_home: int
    corners_fh_away: int
    corners_2h_away: int
    corners_fh_avg_overall: float
    corners_2h_avg_overall: float
    corners_fh_avg_home: float
    corners_2h_avg_home: float
    corners_fh_avg_away: float
    corners_2h_avg_away: float
    corners_fh_over4_overall: int
    corners_2h_over4_overall: int
    corners_fh_over4_home: int
    corners_2h_over4_home: int
    corners_fh_over4_away: int
    corners_2h_over4_away: int
    corners_fh_over4_percentage_overall: int
    corners_2h_over4_percentage_overall: int
    corners_fh_over4_percentage_home: int
    corners_2h_over4_percentage_home: int
    corners_fh_over4_percentage_away: int
    corners_2h_over4_percentage_away: int
    corners_fh_over5_overall: int
    corners_2h_over5_overall: int
    corners_fh_over5_home: int
    corners_2h_over5_home: int
    corners_fh_over5_away: int
    corners_2h_over5_away: int
    corners_fh_over5_percentage_overall: int
    corners_2h_over5_percentage_overall: int
    corners_fh_over5_percentage_home: int
    corners_2h_over5_percentage_home: int
    corners_fh_over5_percentage_away: int
    corners_2h_over5_percentage_away: int
    corners_fh_over6_overall: int
    corners_2h_over6_overall: int
    corners_fh_over6_home: int
    corners_2h_over6_home: int
    corners_fh_over6_away: int
    corners_2h_over6_away: int
    corners_fh_over6_percentage_overall: int
    corners_2h_over6_percentage_overall: int
    corners_fh_over6_percentage_home: int
    corners_2h_over6_percentage_home: int
    corners_fh_over6_percentage_away: int
    corners_2h_over6_percentage_away: int
    attack_num_recoded_matches_overall: int
    dangerous_attacks_num_overall: int
    attacks_num_overall: int
    dangerous_attacks_avg_overall: float
    dangerous_attacks_avg_home: float
    dangerous_attacks_avg_away: float
    attacks_avg_overall: float
    attacks_avg_home: float
    attacks_avg_away: float
    xg_for_avg_overall: float
    xg_for_avg_home: float
    xg_for_avg_away: float
    xg_against_avg_overall: float
    xg_against_avg_home: float
    xg_against_avg_away: float
    additional_info: TeamStatsAdditionalInfo
    goals_scored_min_0_to_10: int
    goals_conceded_min_0_to_10: int
    goals_scored_min_11_to_20: int
    goals_conceded_min_11_to_20: int
    goals_scored_min_21_to_30: int
    goals_conceded_min_21_to_30: int
    goals_scored_min_31_to_40: int
    goals_conceded_min_31_to_40: int
    goals_scored_min_41_to_50: int
    goals_conceded_min_41_to_50: int
    goals_scored_min_51_to_60: int
    goals_conceded_min_51_to_60: int
    goals_scored_min_61_to_70: int
    goals_conceded_min_61_to_70: int
    goals_scored_min_71_to_80: int
    goals_conceded_min_71_to_80: int
    goals_scored_min_81_to_90: int
    goals_conceded_min_81_to_90: int
    goals_all_min_0_to_10: int
    goals_all_min_11_to_20: int
    goals_all_min_21_to_30: int
    goals_all_min_31_to_40: int
    goals_all_min_41_to_50: int
    goals_all_min_51_to_60: int
    goals_all_min_61_to_70: int
    goals_all_min_71_to_80: int
    goals_all_min_81_to_90: int
    goals_all_min_0_to_15: int
    goals_all_min_16_to_30: int
    goals_all_min_31_to_45: int
    goals_all_min_46_to_60: int
    goals_all_min_61_to_75: int
    goals_all_min_76_to_90: int
    goals_scored_min_0_to_15: int
    goals_scored_min_16_to_30: int
    goals_scored_min_31_to_45: int
    goals_scored_min_46_to_60: int
    goals_scored_min_61_to_75: int
    goals_scored_min_76_to_90: int
    goals_conceded_min_0_to_15: int
    goals_conceded_min_16_to_30: int
    goals_conceded_min_31_to_45: int
    goals_conceded_min_46_to_60: int
    goals_conceded_min_61_to_75: int
    goals_conceded_min_76_to_90: int
    goals_scored_min_0_to_10_home: int
    goals_scored_min_11_to_20_home: int
    goals_scored_min_21_to_30_home: int
    goals_scored_min_31_to_40_home: int
    goals_scored_min_41_to_50_home: int
    goals_scored_min_51_to_60_home: int
    goals_scored_min_61_to_70_home: int
    goals_scored_min_71_to_80_home: int
    goals_scored_min_81_to_90_home: int
    goals_scored_min_0_to_15_home: int
    goals_scored_min_16_to_30_home: int
    goals_scored_min_31_to_45_home: int
    goals_scored_min_46_to_60_home: int
    goals_scored_min_61_to_75_home: int
    goals_scored_min_76_to_90_home: int
    goals_conceded_min_0_to_10_home: int
    goals_conceded_min_11_to_20_home: int
    goals_conceded_min_21_to_30_home: int
    goals_conceded_min_31_to_40_home: int
    goals_conceded_min_41_to_50_home: int
    goals_conceded_min_51_to_60_home: int
    goals_conceded_min_61_to_70_home: int
    goals_conceded_min_71_to_80_home: int
    goals_conceded_min_81_to_90_home: int
    goals_conceded_min_0_to_15_home: int
    goals_conceded_min_16_to_30_home: int
    goals_conceded_min_31_to_45_home: int
    goals_conceded_min_46_to_60_home: int
    goals_conceded_min_61_to_75_home: int
    goals_conceded_min_76_to_90_home: int
    goals_all_min_0_to_10_home: int
    goals_all_min_11_to_20_home: int
    goals_all_min_21_to_30_home: int
    goals_all_min_31_to_40_home: int
    goals_all_min_41_to_50_home: int
    goals_all_min_51_to_60_home: int
    goals_all_min_61_to_70_home: int
    goals_all_min_71_to_80_home: int
    goals_all_min_81_to_90_home: int
    goals_all_min_0_to_15_home: int
    goals_all_min_16_to_30_home: int
    goals_all_min_31_to_45_home: int
    goals_all_min_46_to_60_home: int
    goals_all_min_61_to_75_home: int
    goals_all_min_76_to_90_home: int
    goals_scored_min_0_to_10_away: int
    goals_scored_min_11_to_20_away: int
    goals_scored_min_21_to_30_away: int
    goals_scored_min_31_to_40_away: int
    goals_scored_min_41_to_50_away: int
    goals_scored_min_51_to_60_away: int
    goals_scored_min_61_to_70_away: int
    goals_scored_min_71_to_80_away: int
    goals_scored_min_81_to_90_away: int
    goals_scored_min_0_to_15_away: int
    goals_scored_min_16_to_30_away: int
    goals_scored_min_31_to_45_away: int
    goals_scored_min_46_to_60_away: int
    goals_scored_min_61_to_75_away: int
    goals_scored_min_76_to_90_away: int
    goals_conceded_min_0_to_10_away: int
    goals_conceded_min_11_to_20_away: int
    goals_conceded_min_21_to_30_away: int
    goals_conceded_min_31_to_40_away: int
    goals_conceded_min_41_to_50_away: int
    goals_conceded_min_51_to_60_away: int
    goals_conceded_min_61_to_70_away: int
    goals_conceded_min_71_to_80_away: int
    goals_conceded_min_81_to_90_away: int
    goals_conceded_min_0_to_15_away: int
    goals_conceded_min_16_to_30_away: int
    goals_conceded_min_31_to_45_away: int
    goals_conceded_min_46_to_60_away: int
    goals_conceded_min_61_to_75_away: int
    goals_conceded_min_76_to_90_away: int
    goals_all_min_0_to_10_away: int
    goals_all_min_11_to_20_away: int
    goals_all_min_21_to_30_away: int
    goals_all_min_31_to_40_away: int
    goals_all_min_41_to_50_away: int
    goals_all_min_51_to_60_away: int
    goals_all_min_61_to_70_away: int
    goals_all_min_71_to_80_away: int
    goals_all_min_81_to_90_away: int
    goals_all_min_0_to_15_away: int
    goals_all_min_16_to_30_away: int
    goals_all_min_31_to_45_away: int
    goals_all_min_46_to_60_away: int
    goals_all_min_61_to_75_away: int
    goals_all_min_76_to_90_away: int
    name_jp: str | None
    name_tr: str | None
    name_kr: str | None
    name_pt: str | None
    name_ru: str | None
    name_es: str | None
    name_se: str | None
    name_de: str | None
    name_zht: str | None
    name_nl: str | None
    name_it: str | None
    name_fr: str | None
    name_id: str | None
    name_pl: str | None
    name_gr: str | None
    name_dk: str | None
    name_th: str | None
    name_hr: str | None
    name_ro: str | None
    name_in: str | None
    name_no: str | None
    name_hu: str | None
    name_cz: str | None
    name_cn: str | None
    name_ara: str | None
    name_si: str | None
    name_vn: str | None
    name_my: str | None
    name_sk: str | None
    name_rs: str | None
    name_ua: str | None
    name_bg: str | None
    name_lv: str | None
    name_ge: str | None
    name_swa: str | None
    name_kur: str | None
    name_ee: str | None
    name_lt: str | None
    name_ba: str | None
    name_by: str | None
    name_fi: str | None
    women: bool | None
    parent_url: HttpUrl | None
    prediction_risk: int
